### ISSUE TITLE
Final Presentaion

### ISSUE THREAD

**Issue by JiejayLan** [JiejayLan/seniorDesign#36]
Due: 2020/5/21(11:30 AM)

[Past Presentation](https://docs.google.com/presentation/d/1TtG_gyLSrvMxASylZedkYjTrMdcF0sTCWUuRQFIciwg/edit#slide=id.g6c8a9c3559_0_5)

[Final Version](https://open-source-searching-platform.web.app/)

### Structure
- Objective and background(kai)
- User Flow Graph (kai)
- Architectural Design(kai)
  - Explain how frontend, backend and machine learning works together
- Features
  + Search by keywords across three platforms/ Filter by  language and platform(Jie)
    -  Explain four APIs
  + Commit prediction(Yi)
    -  Dataset training ML model
- Difficulties and future plan(Jie)

- Demo(Choose keyword and repo in advance, 3 examples) kai

**Comment by Kaihchen1230** [comment]
this is the link to PPT: https://docs.google.com/presentation/d/10cFDrMP1N4dg8uvJU_9j0wZ_ZX26sUg7dQ5jhRf9hps/edit?usp=sharing
